#!/bin/sh
#
# monitor setup
bspc monitor -d [I] [II] [III] [IV] [V]


#bspc rule -a Alacritty desktop=^1
#bspc rule -a code-oss desktop=^3

# Set environment variables
export PATH="$HOME/.local/bin:$PATH"
export XDG_CURRENT_DESKTOP='bspwm'
## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

run() {
  if ! pidof -q "$1"; then
    "$@" &
  fi
}


# Border
bspc config border_width                3
bspc config border_radius               25
bspc config window_gap                  5
bspc config focused_border_color        "#c80e15"
bspc config normal_border_color         "#3B4252"
bspc config focus_follows_pointer     	true
bspc config pointer_follows_focus    	false
bspc config pointer_follows_monitor   	true
bspc config pointer_motion_interval  	7
bspc config pointer_modifier          	mod4
bspc config pointer_action1           	move
bspc config pointer_action2          	resize_side
bspc config pointer_action3           	resize_corner

# Behavior
bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config single_monocle            	true

bspc config automatic_scheme          	longest_side
bspc config initial_polarity          	second_child
bspc config removal_adjustment        	true

bspc config external_rules_command "${HOME}"/.config/bspwm/src/ExternalRules

bspc rule -a floating_rmpc state=floating rectangle=750x350+3+30
bspc rule -a ChatAi state=floating rectangle=470x665+1445+385
bspc rule -a GeminiAi state=floating rectangle=470x665+1445+385
bspc rule -a ClaudeAi state=floating rectangle=470x665+1445+385
bspc rule -a TerminalDefault state=floating sticky=off rectangle=750x665+3+385
bspc rule -a TerminalPinned state=floating sticky=on rectangle=470x350+1445+30
bspc rule -a Terminalnvim desktop=^3 state=floating sticky=off rectangle=1435x1020+3+30
bspc rule -a Code desktop=^3 state=floating sticky=off rectangle=1435x1020+3+30
bspc rule -a youtube desktop=^3 state=floating sticky=off rectangle=1435x1020+3+30
bspc rule -a qView state=floating center=on sticky=off rectangle=470x350+0+0
bspc rule -a St state=floating rectangle=1120x820+3+30
bspc rule -a YaziTerm state=floating center=on rectangle=900x442+0+0
bspc rule -a Thunar desktop=^1
bspc rule -a Spotify desktop=^4
bspc rule -a vesktop desktop=^5
bspc rule -a Vivaldi-stable desktop=^2


# picom
pkill picom
sleep 0.1
picom &

# Autostart background dengan slideshow 10 menit
~/.local/bin/bg-slideshow

# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# polybar
~/.config/polybar/launch.sh &

#eww
chmod +x ~/.config/eww/scripts/*
#eww daemon && eww open topbar

# dunst untuk widget notifikasi
pgrep -x dunst > /dev/null || dunst &

chmod +x ~/.local/bin/*
update-desktop-database ~/.local/share/applications/

if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    eval "$(dbus-launch --sh-syntax)"
fi

pkill daktilo
daktilo --config ~/.config/daktilo/daktilo.toml --preset ducduggo -d pipewire

